import {grades,courses,topics,sources,courseById,topicById} from './data/catalog.mjs';
import {parseRoute,coursesForGrade,courseProgress,migrateState} from './core.mjs';
const KEY='eko:state:v2', OLD='eko:state:v1';
const LEGACY_KEYS=['eko:studio-step','eko:studio-completed','eko:recall-index','eko:recall-schedule','eko:evidence','eko:timer'];
const $=s=>document.querySelector(s), app=$('#app'), crumbs=$('#crumbs'), toast=$('#toast');
const parse=value=>{try{return JSON.parse(value||'null')}catch{return null}};
function legacySnapshot(){const notes={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('eko:studio-note-'))notes[key.slice(16)]=localStorage.getItem(key)}return {studio:{step:parse(localStorage.getItem('eko:studio-step')),completed:parse(localStorage.getItem('eko:studio-completed'))},recall:parse(localStorage.getItem('eko:recall-schedule'))||[],evidence:parse(localStorage.getItem('eko:evidence'))||[],timer:parse(localStorage.getItem('eko:timer')),notes}}
let state=migrateState(parse(localStorage.getItem(OLD)),parse(localStorage.getItem(KEY)),legacySnapshot());
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function flash(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function meter(value,label='İlerleme'){return `<div class="meter" aria-label="${label}: yüzde ${value}"><i style="--p:${value}%"></i></div><small>%${value} tamamlandı</small>`}
function shell(kicker,title,body,aside=''){return `<section class="page-head"><div><p class="kicker">${kicker}</p><h1 tabindex="-1">${title}</h1><p class="lede">${body}</p></div>${aside}</section>`}
function setCrumbs(items){crumbs.innerHTML=items.map((x,i)=>i===items.length-1?`<span aria-current="page">${x.label}</span>`:`<a href="${x.href}">${x.label}</a><b>›</b>`).join('')}
function courseTopics(c){return c.topicIds.map(topicById).filter(Boolean)}
function preserveDraft(){const note=$('#note');const id=note?.dataset.topic;if(note&&id){state.notes[id]=note.value;save()}}
function home(){setCrumbs([]);const completed=state.completedTopics.length;app.innerHTML=`${shell('BURSA ULUDAĞ ÜNİVERSİTESİ · EKONOMETRİ','Kaçıncı sınıfsın?','Dersi bulmak için menü çözmeyeceksin. Sınıfını seç; dönem derslerini gör; çalışmaya gir.',`<div class="orbit" aria-hidden="true"><b>${completed}</b><span>konu bitti</span></div>`)}<section class="grade-grid">${grades.map(g=>`<a class="grade-card" href="#/sinif/${g.id}" style="--accent:${g.color}"><span class="grade-no">0${g.id}</span><div><p>${g.eyebrow}</p><h2>${g.label}</h2><h3>${g.title}</h3><span>${g.summary}</span></div><i>Rotayı aç →</i></a>`).join('')}</section><section class="manifest"><p class="kicker">BÖLÜMÜN KEMİĞİ</p><h2>Ekonomik soruyu, ölçülebilir kanıta çevir.</h2><div class="manifest-grid"><article><b>01</b><h3>İktisadı anla</h3><p>Mekanizmayı ve soruyu kur.</p></article><article><b>02</b><h3>Veriyi sorgula</h3><p>Ölçümün ne söylediğini ayır.</p></article><article><b>03</b><h3>Modeli sınırla</h3><p>Varsayımları görünür yap.</p></article><article><b>04</b><h3>Sonucu savun</h3><p>Belirsizliği dürüstçe raporla.</p></article></div></section>`}
function gradePage(id){const g=grades.find(x=>x.id===id);if(!g)return notFound();const list=coursesForGrade(courses,id);state.selectedGradeId=id;save();setCrumbs([{label:'Sınıflar',href:'#/'},{label:g.label}]);app.innerHTML=`${shell(g.eyebrow,g.label,g.summary,`<div class="big-number">0${g.id}</div>`)}${list.length?`<div class="term"><div class="term-label"><span>5. yarıyıl · güz</span><b>${list.length} doğrulanmış ders</b></div><div class="course-grid">${list.map(courseCard).join('')}</div></div>`:`<section class="empty-state"><span>DOĞRULAMA KAPISI</span><h2>Bu sınıfın resmî dersleri henüz yayınlanmadı.</h2><p>Yanlış veya eski müfredatı “dolu görünsün” diye göstermiyoruz. Aktif BUÜ eğitim planıyla satır satır eşleştirme sürüyor.</p><a href="${sources.program.url}" target="_blank" rel="noreferrer">Resmî program kaynağı ↗</a></section>`}`}
function courseCard(c){const p=courseProgress(c.topicIds,state.completedTopics);return `<a class="course-card" href="#/ders/${c.id}"><div><span class="verified">✓ Resmî kayıt doğrulandı</span><b>${c.code}</b></div><h2>${c.name}</h2><p>${c.term}. yarıyıl · ${c.type} · ${c.weeklyHours} saat/hafta</p>${meter(p)}<i>Derse gir →</i></a>`}
function coursePage(id){const c=courseById(id);if(!c)return notFound();const g=grades.find(x=>x.id===c.gradeId),p=courseProgress(c.topicIds,state.completedTopics),list=courseTopics(c);setCrumbs([{label:'Sınıflar',href:'#/'},{label:g.label,href:`#/sinif/${g.id}`},{label:c.name}]);app.innerHTML=`${shell(`${c.code} · ${c.term}. YARIYIL`,c.name,'Sınava ezber listesiyle değil, birbirine bağlanan yedi düşünce adımıyla hazırlan.',`<div class="score"><b>${p}</b><span>% rota</span></div>`)}<section class="official"><div><p class="kicker">RESMÎ KAPSAM</p><h2>Ders kimliği</h2></div><dl><div><dt>Tür</dt><dd>${c.type}</dd></div><div><dt>Dil</dt><dd>${c.language}</dd></div><div><dt>Haftalık</dt><dd>${c.weeklyHours} saat</dd></div><div><dt>Ön koşul</dt><dd>${c.prerequisite}</dd></div><div class="warning"><dt>AKTS</dt><dd>${c.ects.join(' / ')} <button class="why" data-info="${esc(c.verificationNote)}">Neden iki değer?</button></dd></div></dl></section><section class="route-section"><div class="section-title"><div><p class="kicker">RASATHANE ANLATIMI</p><h2>${list.length} duraklık hazırlık rotası</h2><p>İlk yedi resmî öğretim haftasından türetilmiş hazırlık yolu; garanti vize kapsamı değildir.</p></div>${meter(p,'Ders ilerlemesi')}</div><div class="topic-list">${list.map(t=>{const done=state.completedTopics.includes(t.id);return `<a href="#/ders/${c.id}/konu/${t.id}" class="topic-row ${done?'done':''}"><span class="topic-index">${done?'✓':String(t.n).padStart(2,'0')}</span><div><b>${t.tag}</b><h3>${t.title}</h3></div><span>${t.time} dk</span><i>→</i></a>`}).join('')}</div></section><section class="source-strip"><div><span>KAYNAK İZİ</span><b>Resmî bilgi ile özgün anlatım karışmaz.</b></div><a href="${sources.course.url}" target="_blank" rel="noreferrer">Ders öğretim planı ↗</a></section>`}
function topicPage(cid,tid){const c=courseById(cid),t=topicById(tid);if(!c||!t||!c.topicIds.includes(tid))return notFound();const g=grades.find(x=>x.id===c.gradeId),list=courseTopics(c),position=list.findIndex(x=>x.id===t.id),done=state.completedTopics.includes(t.id),q=state.quizResults[t.id];setCrumbs([{label:g.label,href:`#/sinif/${g.id}`},{label:c.name,href:`#/ders/${c.id}`},{label:t.title}]);app.innerHTML=`<article class="study">${shell(`DURAK ${String(t.n).padStart(2,'0')} · ${t.time} DK`,t.title,t.summary,`<button class="complete ${done?'is-done':''}" data-complete="${t.id}">${done?'✓ Tamamlandı':'Konuyu tamamla'}</button>`)}<div class="study-grid"><section class="concept"><span>ANA FİKİR</span><p>${t.why}</p><div class="formula">${t.formula}</div></section><section><span>ÇÖZÜMLÜ ÖRNEK</span><p>${t.example}</p></section><section class="trap"><span>HATA RADARI</span><p>${t.mistake}</p></section></div><section class="quiz"><p class="kicker">60 SANİYELİK KONTROL</p><h2 id="quiz-question">${t.q}</h2><div class="answers" role="group" aria-labelledby="quiz-question">${t.options.map((o,i)=>`<button data-answer="${i}" data-topic="${t.id}" aria-pressed="${q===i}" class="${q===i?(i===t.answer?'correct':'wrong'):''}">${String.fromCharCode(65+i)} · ${o}</button>`).join('')}</div><p class="feedback" role="status" aria-live="polite">${q!==undefined?`${q===t.answer?'Doğru.':'Tekrar düşün.'} ${t.explain}`:''}</p></section><section class="notes"><div><p class="kicker">KENDİ CÜMLENLE</p><h2>Bunu yarınki kendine anlat.</h2></div><textarea id="note" data-topic="${t.id}" placeholder="Formülü değil, mantığı yaz…">${esc(state.notes[t.id]||'')}</textarea><button data-save-note="${t.id}">Notu kaydet</button></section><nav class="next-topic">${position>0?`<a href="#/ders/${c.id}/konu/${list[position-1].id}">← Önceki</a>`:'<span></span>'}${position<list.length-1?`<a href="#/ders/${c.id}/konu/${list[position+1].id}">Sıradaki →</a>`:`<a href="#/ders/${c.id}">Rotaya dön →</a>`}</nav></article>`}
function notFound(){setCrumbs([]);app.innerHTML=shell('404','Bu kapı yok.','Rota değişmiş olabilir. Ana sınıf seçimine dön.',`<a class="primary" href="#/">Ana sayfa</a>`)}
function render({focusHeading=true}={}){const r=parseRoute(location.hash);state.lastRoute=location.hash||'#/';save();({home,grade:()=>gradePage(r.gradeId),course:()=>coursePage(r.courseId),topic:()=>topicPage(r.courseId,r.topicId),notFound}[r.name]||notFound)();scrollTo(0,0);if(focusHeading)setTimeout(()=>app.querySelector('h1')?.focus(),0)}
addEventListener('hashchange',render);addEventListener('DOMContentLoaded',()=>{if(!location.hash)location.hash='#/';else render()});
document.addEventListener('click',e=>{const skip=e.target.closest('[data-skip]');if(skip){e.preventDefault();app.focus();return}const info=e.target.closest('[data-info]');if(info)flash(info.dataset.info);const complete=e.target.closest('[data-complete]');if(complete){preserveDraft();const id=complete.dataset.complete;state.completedTopics=state.completedTopics.includes(id)?state.completedTopics.filter(x=>x!==id):[...state.completedTopics,id];save();render();flash('İlerleme kaydedildi.')}const ans=e.target.closest('[data-answer]');if(ans){preserveDraft();state.quizResults[ans.dataset.topic]=Number(ans.dataset.answer);save();const index=Number(ans.dataset.answer);render({focusHeading:false});setTimeout(()=>document.querySelector(`[data-answer="${index}"]`)?.focus(),0)}const note=e.target.closest('[data-save-note]');if(note){state.notes[note.dataset.saveNote]=$('#note').value.trim();save();flash('Notun bu cihazda kaydedildi.')}});
$('#reset-progress').addEventListener('click',()=>{if(confirm('Tüm ilerleme, test ve notları sıfırlamak istiyor musun?')){localStorage.removeItem(KEY);localStorage.removeItem(OLD);for(const key of LEGACY_KEYS)localStorage.removeItem(key);for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith('eko:studio-note-'))localStorage.removeItem(key)}state=migrateState();render();flash('İlerleme sıfırlandı.')}});