import {courses, topics, courseById, topicById} from './data/catalog.mjs';
import {concepts, learningUnits, conceptById, learningUnitById} from './learning-data.mjs';
import {migrateLearningState, parseLearningRoute, validateLearningArchitecture} from './learning-core.mjs';

const KEY='eko:m3:v1', LEGACY='eko:last-topic', JOURNEY_KEY='eko:journey:v1';
const app=document.querySelector('#app'), crumbs=document.querySelector('#crumbs');
const esc=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const read=value=>{try{return JSON.parse(value||'null')}catch{return null}};
const architectureErrors=validateLearningArchitecture({units:learningUnits,concepts,courseIds:courses.map(({id})=>id),topicIds:topics.map(({id})=>id)});
if(architectureErrors.length) throw new Error(`M3 öğrenme mimarisi geçersiz: ${architectureErrors.join('; ')}`);
let state=migrateLearningState(read(localStorage.getItem(KEY)),localStorage.getItem(LEGACY));
const defaultJourney={version:1,step:0,lab:{omitted:'Beklentiler',strength:3},card:{question:'Gelir arttığında hane tüketimi nasıl değişir?',y:'Hane tüketimi',x:'Hane geliri',omitted:'Beklentiler',interpretation:'Gelir arttığında tüketimin artmasını beklerim.',limitation:''},complete:false};
let journey={...defaultJourney,...(read(localStorage.getItem(JOURNEY_KEY))||{})};
journey.lab={...defaultJourney.lab,...(journey.lab||{})}; journey.card={...defaultJourney.card,...(journey.card||{})};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const saveJourney=()=>localStorage.setItem(JOURNEY_KEY,JSON.stringify(journey));
const unitHref=unit=>`#/ders/${unit.relatedCourseIds[0]}/konu/${unit.topicId}`;
const setCrumbs=items=>{crumbs.innerHTML=items.map((item,index)=>index===items.length-1?`<span aria-current="page">${esc(item.label)}</span>`:`<a href="${item.href}">${esc(item.label)}</a><b>›</b>`).join('')};

function productHome(){
 setCrumbs([]);
 app.innerHTML=`<section class="reset-hero" data-product-home><p class="kicker">EKONOMİK SORUDAN KANITA</p><h1 tabindex="-1">Bir ekonomik soruyu modele ve savunulabilir bir çıktıya dönüştür.</h1><p class="reset-lede">Kavramı adım adım öğren, modelin sınırlarını dene ve kendi Mini Model Card’ını üret.</p><div class="hero-actions"><a class="primary reset-primary" href="#/basla">${journey.step>0?'Yolculuğa devam et':'Örnek yolculuğu başlat'} →</a><span>İlk örnek: Modelleme kavramları · yaklaşık 8 dakika</span></div></section>
 <section class="path-grid" aria-labelledby="paths-title"><div class="section-title"><div><p class="kicker">HEDEFİNİ SEÇ</p><h2 id="paths-title">Burada ne yapmak istiyorsun?</h2></div></div><article><span>01</span><h3>Programımı takip et</h3><p>Derslerinde nerede olduğunu ve sıradaki çalışma adımını gör.</p><a href="#/sinif/3">3. sınıf rotasını aç →</a></article><article><span>02</span><h3>Bir kavram öğren</h3><p>Kavramların ön koşullarını ve birbirleriyle bağını keşfet.</p><a href="#/atlas">Kavram haritasını aç →</a></article><article><span>03</span><h3>Model dene ve araştır</h3><p>Bir varsayımı değiştir, yorumunu yaz ve araştırma çıktısı üret.</p><a href="#/basla" data-start-step="2">Laboratuvara geç →</a></article></section>
 <aside class="scope-note"><strong>Bağımsız ve kurumdan taşınabilir.</strong> BUÜ programı ilk doğrulama alanıdır; ürünün omurgası ders koduna bağlı değildir.</aside>`;
 setTimeout(()=>app.querySelector('h1')?.focus(),0);
}

const stages=[
 {name:'Anla',title:'Model neden gerçeğin kopyası değildir?',body:`<p class="stage-lead">Bir model, gerçek dünyanın tamamını değil; cevaplamak istediğin soru için gerekli mekanizmayı seçer.</p><div class="idea-card"><span>ANA FİKİR</span><strong>Model = bilinçli ve sınanabilir bir sadeleştirme</strong><p>“Gelir tüketimi nasıl etkiler?” sorusunda gelir <b>X</b>, tüketim <b>Y</b>, seçmediğin diğer etkiler ise <b>u</b> içinde düşünülür.</p></div>`},
 {name:'Örnekle',title:'Soruyu değişkenlere ayır',body:`<div class="model-diagram" aria-label="Gelir, tüketim ve model dışında kalan etkiler diyagramı"><div><small>AÇIKLAYICI</small><b>Gelir (X)</b></div><span aria-hidden="true">→</span><div><small>AÇIKLANAN</small><b>Tüketim (Y)</b></div><div class="outside"><small>MODEL DIŞINDA</small><b>Beklenti · eğitim · zevkler (u)</b></div></div><div class="equation">Y = f(X) + u</div><p>Formülün işi gerçeği küçültmek değil, hangi ilişkinin sınanacağını açık etmektir.</p>`},
 {name:'Dene',title:'Modelin sınırını değiştir',body:`<div class="lab-grid"><div><label for="omitted">Model dışında hangi etki kalsın?</label><select id="omitted" data-lab-field="omitted"><option>Beklentiler</option><option>Eğitim</option><option>Zevkler</option></select><label for="strength">Bu etkinin önemi: <output id="strength-output">${journey.lab.strength}/5</output></label><input id="strength" data-lab-field="strength" type="range" min="1" max="5" value="${journey.lab.strength}"></div><div class="lab-result" aria-live="polite"><span>MODEL OKUMASI</span><p id="lab-reading"></p><code>Y = f(Gelir) + u</code></div></div><noscript>Statik alternatif: Gelir X, tüketim Y’dir. Beklentiler model dışında bırakılırsa etkileri u içinde kalır ve yorumun kesinliği azalır.</noscript>`},
 {name:'Kontrol Et',title:'Sadeleştirme ile eksikliği ayır',body:`<fieldset class="journey-quiz"><legend>Bir modelin temel işi nedir?</legend><label><input type="radio" name="journey-answer" value="0"> Gerçeği eksiksiz kopyalamak</label><label><input type="radio" name="journey-answer" value="1"> Sınanabilir bir sadeleştirme yapmak</label><label><input type="radio" name="journey-answer" value="2"> Model dışındaki etkileri önemsiz saymak</label><button type="button" data-check-answer>Yanıtı kontrol et</button><p role="status" class="quiz-result"></p></fieldset>`},
 {name:'Kanıtla',title:'Mini Model Card’ını oluştur',body:`<form class="model-card-form"><div><label for="card-question">Ekonomik soru</label><input id="card-question" data-card-field="question" value="${esc(journey.card.question)}" required></div><div><label for="card-y">Açıklanan değişken (Y)</label><input id="card-y" data-card-field="y" value="${esc(journey.card.y)}" required></div><div><label for="card-x">Açıklayıcı değişken (X)</label><input id="card-x" data-card-field="x" value="${esc(journey.card.x)}" required></div><div><label for="card-omitted">Model dışında kalan etkiler (u)</label><input id="card-omitted" data-card-field="omitted" value="${esc(journey.card.omitted)}" required></div><div class="wide"><label for="card-interpretation">Senin yorumun</label><textarea id="card-interpretation" data-card-field="interpretation" required>${esc(journey.card.interpretation)}</textarea></div><div class="wide"><label for="card-limitation">Modelin sınırlılığı</label><textarea id="card-limitation" data-card-field="limitation" placeholder="Bu model neyi açıklayamaz?" required>${esc(journey.card.limitation)}</textarea></div><button class="primary" type="submit">Model Card’ı oluştur</button></form><section class="model-card-output" ${journey.complete?'':'hidden'} aria-live="polite"></section>`}
];
function renderJourney(){
 journey.step=Math.max(0,Math.min(stages.length-1,Number(journey.step)||0)); saveJourney();
 const stage=stages[journey.step]; setCrumbs([{label:'Ana sayfa',href:'#/'},{label:'İlk araştırman'}]);
 app.innerHTML=`<article class="journey" data-journey-step="${journey.step+1}"><header class="journey-head"><div><p class="kicker">İLK ARAŞTIRMAN · MODELLEME KAVRAMLARI</p><h1 tabindex="-1">${stage.title}</h1></div><span>${journey.step+1} / ${stages.length}</span></header><nav class="stepper" aria-label="Öğrenme adımları">${stages.map((item,index)=>`<button type="button" data-go-step="${index}" ${index===journey.step?'aria-current="step"':''} ${index>journey.step&&!journey.complete?'disabled':''}><span>${index+1}</span>${item.name}</button>`).join('')}</nav><section class="stage-panel"><p class="kicker">${journey.step+1} · ${stage.name.toUpperCase()}</p>${stage.body}</section><nav class="journey-actions">${journey.step?'<button type="button" data-prev-step>← Önceki</button>':'<a href="#/">← Ana sayfa</a>'}${journey.step<stages.length-1?'<button class="primary" type="button" data-next-step>Devam et →</button>':''}</nav></article>`;
 if(journey.step===2){const select=app.querySelector('#omitted'); select.value=journey.lab.omitted; updateLab()}
 if(journey.step===4&&journey.complete) renderCard();
 setTimeout(()=>app.querySelector('h1')?.focus(),0);
}
function updateLab(){const strength=Number(journey.lab.strength), omitted=journey.lab.omitted; const output=app.querySelector('#strength-output'), reading=app.querySelector('#lab-reading'); if(output)output.textContent=`${strength}/5`; if(reading)reading.textContent=`${omitted} modelin dışında ve etkisi ${strength>=4?'yüksek':strength>=2?'orta':'düşük'} kabul edildi. Bu etki gelirle de ilişkiliyse, “gelirin etkisi” yorumun daha dikkatli yapılmalıdır.`}
function renderCard(){const output=app.querySelector('.model-card-output'); if(!output)return; output.hidden=false; output.innerHTML=`<p class="kicker">ÜRETİLEN ÇIKTI</p><h2>Mini Model Card</h2><dl><div><dt>Ekonomik soru</dt><dd>${esc(journey.card.question)}</dd></div><div><dt>Y</dt><dd>${esc(journey.card.y)}</dd></div><div><dt>X</dt><dd>${esc(journey.card.x)}</dd></div><div><dt>u</dt><dd>${esc(journey.card.omitted)}</dd></div><div><dt>Yorum</dt><dd>${esc(journey.card.interpretation)}</dd></div><div><dt>Sınırlılık</dt><dd>${esc(journey.card.limitation)}</dd></div></dl><p><strong>Bu bir sonuç değil, savunulabilir araştırmaya başlangıç kaydıdır.</strong></p>`; output.focus?.()}

function atlasPage(){setCrumbs([{label:'Ana sayfa',href:'#/'},{label:'Kavram haritası'}]);app.innerHTML=`<section class="page-head"><div><p class="kicker">KAVRAM HARİTASI</p><h1 tabindex="-1">Veriden Modele</h1><p class="lede">Bir kavramın neye dayandığını ve sonra nereye bağlandığını gör.</p></div></section><ol class="atlas-route" aria-label="Veriden Modele kavram rotası">${concepts.map((concept,index)=>`<li><span>${String(index+1).padStart(2,'0')}</span><a href="#/atlas/kavram/${encodeURIComponent(concept.id)}"><strong>${esc(concept.title)}</strong><small>${concept.prerequisiteIds.length?`${concept.prerequisiteIds.length} ön koşul`:'Başlangıç'}</small></a></li>`).join('')}</ol>`}
function conceptPage(conceptId){const concept=conceptById(conceptId),unit=concept&&learningUnitById(concept.unitId),topic=unit&&topicById(unit.topicId);if(!concept||!unit||!topic)return;const course=courseById(unit.relatedCourseIds[0]);setCrumbs([{label:'Ana sayfa',href:'#/'},{label:'Kavram haritası',href:'#/atlas'},{label:concept.title}]);app.innerHTML=`<article class="concept-page"><section class="page-head"><div><p class="kicker">KAVRAM BAĞLANTISI</p><h1 tabindex="-1">${esc(concept.title)}</h1><p class="lede">${esc(unit.objective)}</p></div></section><div class="concept-map"><section><p class="kicker">NEYE DAYANIYOR?</p><p>${concept.prerequisiteIds.length?concept.prerequisiteIds.map(id=>`<a href="#/atlas/kavram/${id}">${esc(conceptById(id)?.title)}</a>`).join(' · '):'Bu rotanın başlangıç kavramı.'}</p></section><section><p class="kicker">NASIL ÖĞRENECEKSİN?</p><h2>${esc(topic.title)}</h2><p>${esc(unit.recap)}</p>${unit.id==='modelleme-kavramlari'?'<a class="primary" href="#/basla">Aşamalı yolculuğu başlat →</a>':`<a href="${unitHref(unit)}">Ders içeriğini aç →</a>`}</section><section><p class="kicker">PROGRAM BAĞLAMI</p><h2>${esc(course?.name||'')}</h2><p>Bu bağlantı ilk doğrulama alanıdır; kavram kimliği ders kodundan bağımsızdır.</p></section></div></article>`}
function enhanceTopic(){const match=location.hash.match(/^#\/ders\/([^/]+)\/konu\/([^/]+)$/);if(!match)return;let topicId;try{topicId=decodeURIComponent(match[2])}catch{return}const unit=learningUnitById(topicId);if(!unit)return;const study=app.querySelector('.study');if(!study||study.dataset.learningUnitId)return;study.dataset.learningUnitId=unit.id;state={version:1,lastUnitId:unit.id};save();if(unit.id==='modelleme-kavramlari') study.querySelector('.page-head')?.insertAdjacentHTML('afterend','<aside class="reset-invite"><strong>Bu kavramın yeni aşamalı deneyimi hazır.</strong><a class="primary" href="#/basla">Anla → Örnekle → Dene → Kanıtla</a></aside>')}
function renderM3(){const route=parseLearningRoute(location.hash);if(location.hash==='#/'||location.hash==='')productHome();else if(location.hash==='#/basla')renderJourney();else if(route?.name==='atlas')atlasPage();else if(route?.name==='concept')conceptPage(route.conceptId);else enhanceTopic();if(route)setTimeout(()=>app.querySelector('h1')?.focus(),0)}
function bind(){document.addEventListener('click',event=>{const start=event.target.closest('[data-start-step]');if(start){journey.step=Number(start.dataset.startStep);saveJourney()}const next=event.target.closest('[data-next-step]');if(next){journey.step=Math.min(4,journey.step+1);saveJourney();renderJourney()}const prev=event.target.closest('[data-prev-step]');if(prev){journey.step=Math.max(0,journey.step-1);saveJourney();renderJourney()}const go=event.target.closest('[data-go-step]');if(go&&!go.disabled){journey.step=Number(go.dataset.goStep);saveJourney();renderJourney()}const check=event.target.closest('[data-check-answer]');if(check){const selected=app.querySelector('[name="journey-answer"]:checked');const result=app.querySelector('.quiz-result');result.textContent=!selected?'Önce bir yanıt seç.':selected.value==='1'?'Doğru. Model, soruya yarayan ilişkiyi sınanabilir biçimde sadeleştirir.':'Tekrar düşün. Model ne gerçeği kopyalar ne de dışarıda kalan etkileri önemsiz sayar.'}});document.addEventListener('input',event=>{const lab=event.target.dataset.labField;if(lab){journey.lab[lab]=lab==='strength'?Number(event.target.value):event.target.value;journey.card.omitted=journey.lab.omitted;saveJourney();updateLab()}const card=event.target.dataset.cardField;if(card){journey.card[card]=event.target.value;journey.complete=false;saveJourney()}});document.addEventListener('submit',event=>{if(!event.target.matches('.model-card-form'))return;event.preventDefault();journey.complete=true;saveJourney();renderCard()});const reset=document.querySelector('#reset-progress');reset?.addEventListener('click',()=>setTimeout(()=>{if(!localStorage.getItem('eko:state:v2'))return;localStorage.removeItem(KEY);localStorage.removeItem(LEGACY);localStorage.removeItem(JOURNEY_KEY);state=migrateLearningState();journey=structuredClone(defaultJourney)},0))}
addEventListener('hashchange',renderM3);addEventListener('DOMContentLoaded',()=>{bind();renderM3()});
