import {courses, topics, courseById, topicById} from './data/catalog.mjs';
import {concepts, learningUnits, conceptById, learningUnitById} from './learning-data.mjs';
import {migrateLearningState, parseLearningRoute, validateLearningArchitecture} from './learning-core.mjs';
const KEY='eko:m3:v1',LEGACY='eko:last-topic',app=document.querySelector('#app'),crumbs=document.querySelector('#crumbs');
const esc=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const read=value=>{try{return JSON.parse(value||'null')}catch{return null}};
const architectureErrors=validateLearningArchitecture({units:learningUnits,concepts,courseIds:courses.map(({id})=>id),topicIds:topics.map(({id})=>id)});
if(architectureErrors.length)throw new Error(`M3 öğrenme mimarisi geçersiz: ${architectureErrors.join('; ')}`);
let state=migrateLearningState(read(localStorage.getItem(KEY)),localStorage.getItem(LEGACY));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const unitHref=unit=>`#/ders/${unit.relatedCourseIds[0]}/konu/${unit.topicId}`;
const setCrumbs=items=>{crumbs.innerHTML=items.map((item,index)=>index===items.length-1?`<span aria-current="page">${esc(item.label)}</span>`:`<a href="${item.href}">${esc(item.label)}</a><b>›</b>`).join('')};
function ensureHeaderLink(){const actions=document.querySelector('.header-actions');if(actions&&!actions.querySelector('[href="#/atlas"]'))actions.insertAdjacentHTML('afterbegin','<a href="#/atlas">Atlas</a>')}
function homeEnhancement(){if(app.querySelector('[data-m3-home]'))return;const last=learningUnitById(state.lastUnitId),topic=last&&topicById(last.topicId);const html=`<section class="m3-entry-grid" data-m3-home aria-label="Öğrenme yolları"><article><p class="kicker">DERS KODUNDAN BAĞIMSIZ</p><h2>Veriden Modele Atlası</h2><p>Kavramı, ön koşullarını ve ilişkili dersi tek rotada gör.</p><a class="primary" href="#/atlas">Atlası aç →</a></article><article data-last-learning><p class="kicker">SON ÇALIŞMA</p><h2>${last?esc(topic?.title||last.id):'Henüz bir konu açmadın'}</h2><p>${last?'Kaldığın öğrenme birimine tek etkileşimle dön.':'Bir konu açtığında dönüş kısayolu burada görünecek.'}</p>${last?`<a class="primary" href="${unitHref(last)}">Son konuya dön →</a>`:'<a href="#/atlas">İlk kavramı seç →</a>'}</article></section>`;app.querySelector('.page-head')?.insertAdjacentHTML('afterend',html)}
function atlasPage(){setCrumbs([{label:'Ana sayfa',href:'#/'},{label:'Atlas'}]);app.innerHTML=`<section class="page-head"><div><p class="kicker">ATLAS · İLK ÇAPRAZ ROTA</p><h1 tabindex="-1">Veriden Modele</h1><p class="lede">Ders kodundan bağımsız kavram ağı. Her düğüm, ön koşulları ve ilişkili program dersini aynı kanonik öğrenme birimine bağlar.</p></div><div class="orbit" aria-hidden="true"><b>${concepts.length}</b><span>kavram</span></div></section><ol class="atlas-route" aria-label="Veriden Modele kavram rotası">${concepts.map((concept,index)=>`<li><span>${String(index+1).padStart(2,'0')}</span><a href="#/atlas/kavram/${encodeURIComponent(concept.id)}"><strong>${esc(concept.title)}</strong><small>${concept.prerequisiteIds.length?`${concept.prerequisiteIds.length} ön koşul`:'Başlangıç düğümü'}</small></a></li>`).join('')}</ol><aside class="m3-disclosure"><strong>Kapsam:</strong> Bu ilk uygulanmış Atlas dilimi, mevcut 7 öğrenme birimini bağlar; tek bir kurumun ders kodu Atlas kimliği olarak kullanılmaz.</aside>`}
function conceptPage(conceptId){const concept=conceptById(conceptId),unit=concept&&learningUnitById(concept.unitId),topic=unit&&topicById(unit.topicId);if(!concept||!unit||!topic)return;const course=courseById(unit.relatedCourseIds[0]),prerequisites=concept.prerequisiteIds.map(conceptById).filter(Boolean);setCrumbs([{label:'Ana sayfa',href:'#/'},{label:'Atlas',href:'#/atlas'},{label:concept.title}]);app.innerHTML=`<article class="concept-page"><section class="page-head"><div><p class="kicker">ATLAS KAVRAMI · ${String(concept.order).padStart(2,'0')}</p><h1 tabindex="-1">${esc(concept.title)}</h1><p class="lede">${esc(unit.objective)}</p></div></section><div class="concept-map"><section><p class="kicker">ÖN KOŞULLAR</p>${prerequisites.length?`<ul>${prerequisites.map(item=>`<li><a href="#/atlas/kavram/${encodeURIComponent(item.id)}">${esc(item.title)}</a></li>`).join('')}</ul>`:'<p>Bu rota için başlangıç düğümü; tanımlı ön koşul yok.</p>'}</section><section><p class="kicker">ÖĞRENME ADIMI</p><h2>${esc(topic.title)}</h2><p>${esc(unit.recap)}</p><a class="primary" href="${unitHref(unit)}">Öğrenme adımını aç →</a></section><section><p class="kicker">İLİŞKİLİ DERSLER</p><h2>${esc(course?.name||unit.relatedCourseIds[0])}</h2><p>${esc(course?.code||'')} · ${course?.term?`${course.term}. yarıyıl`:''}</p><a href="#/ders/${encodeURIComponent(unit.relatedCourseIds[0])}">Ders rotasını gör →</a></section></div></article>`}
function enhanceTopic(){const match=location.hash.match(/^#\/ders\/([^/]+)\/konu\/([^/]+)$/);if(!match)return;let topicId;try{topicId=decodeURIComponent(match[2])}catch{return}const unit=learningUnitById(topicId);if(!unit)return;const study=app.querySelector('.study');if(!study||study.dataset.learningUnitId)return;const prerequisiteLinks=unit.prerequisiteIds.map(id=>{const item=conceptById(id);return item?`<a href="#/atlas/kavram/${encodeURIComponent(id)}">${esc(item.title)}</a>`:''}).filter(Boolean);study.dataset.learningUnitId=unit.id;study.dataset.templateSections='8';study.querySelector('.page-head')?.insertAdjacentHTML('afterend',`<section class="learning-contract" aria-label="Öğrenme birimi sözleşmesi"><div><p class="kicker">1 · ÖĞRENME HEDEFİ</p><p>${esc(unit.objective)}</p></div><div><p class="kicker">2 · ÖN KOŞUL</p><p>${prerequisiteLinks.length?prerequisiteLinks.join(' · '):'Tanımlı ön koşul yok.'}</p></div><div><p class="kicker">5 · GÖRSEL AÇIKLAMA</p><p>${esc(unit.visualExplanation)}</p></div></section>`);app.querySelector('.quiz')?.insertAdjacentHTML('afterend',`<section class="learning-recap"><p class="kicker">8 · ÖZET VE KAYNAK</p><h2>Bir cümlede toparla</h2><p>${esc(unit.recap)}</p><ul>${unit.sourceRefs.map(source=>`<li><a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label)} ↗</a></li>`).join('')}</ul><a href="#/atlas/kavram/${encodeURIComponent(unit.conceptId)}">Bu kavramı Atlas’ta gör →</a></section>`);state={version:1,lastUnitId:unit.id};save()}
function renderM3(){ensureHeaderLink();const route=parseLearningRoute(location.hash);if(route?.name==='atlas')atlasPage();else if(route?.name==='concept')conceptPage(route.conceptId);else if(location.hash==='#/')homeEnhancement();else enhanceTopic();if(route)setTimeout(()=>app.querySelector('h1')?.focus(),0)}
function bindReset(){const reset=document.querySelector('#reset-progress');if(!reset)return;const nativeConfirm=window.confirm.bind(window);let confirmedReset=false;window.confirm=message=>{const result=nativeConfirm(message);if(message==='Tüm ilerleme, test ve notları sıfırlamak istiyor musun?')confirmedReset=result;return result};reset.addEventListener('click',()=>{if(!confirmedReset)return;localStorage.removeItem(KEY);localStorage.removeItem(LEGACY);state=migrateLearningState();confirmedReset=false})}
addEventListener('hashchange',renderM3);addEventListener('DOMContentLoaded',()=>{bindReset();renderM3()});
