import {academicCatalog} from './data/academic-catalog.mjs';
import {offerings as sourceOfferings,sourceSnapshots} from './data/timetable.mjs';
export const MAPPING_STATUSES=Object.freeze(['mapped','mapped-with-anomaly','ambiguous','unmatched']);
const normalize=value=>String(value??'').toLocaleUpperCase('tr-TR').normalize('NFC').replace(/[’']/g,"'").replace(/[^0-9A-ZÇĞİÖŞÜ']/g,' ').replace(/\s+/g,' ').trim();
const typeOf=value=>value==='Z'?'required':value==='S'?'elective':null;
const joined=academicCatalog.curriculumCourses.map(relation=>({relation,course:academicCatalog.courses.find(course=>course.id===relation.courseId)}));
const candidatesFor=offering=>joined.filter(({relation})=>relation.semester===offering.semester&&(!typeOf(offering.courseType)||relation.courseType===typeOf(offering.courseType)));
export function getDepartmentCode(item){const code=String(item?.printedCourseCode??'').trim().toLocaleUpperCase('tr-TR').normalize('NFC');return code.match(/^[A-ZÇĞİÖŞÜ]+/u)?.[0]??''}
export function getDepartmentCodes(items=[]){return [...new Set(items.map(getDepartmentCode).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr-TR'))}
export function reconcileOffering(offering){const candidates=candidatesFor(offering),code=normalize(offering.printedCourseCode),title=normalize(offering.sourceTitle),exact=candidates.filter(({course})=>normalize(course.courseCode)===code&&normalize(course.sourceTitle)===title),titleMatches=candidates.filter(({course})=>normalize(course.sourceTitle)===title),codeMatches=candidates.filter(({course})=>normalize(course.courseCode)===code);let selected=null,status='unmatched',reason='no-composite-match',anomalyRefs=[];if(exact.length===1){selected=exact[0];anomalyRefs=[...(selected.course.anomalyRefs||[])];status=anomalyRefs.length?'mapped-with-anomaly':'mapped';reason='code-title-semester-type'}else if(exact.length>1){status='ambiguous';reason='multiple-exact-composite-matches'}else if(titleMatches.length===1){selected=titleMatches[0];status='mapped-with-anomaly';reason='title-semester-type-with-printed-code-mismatch';anomalyRefs=['offering-printed-code-mismatch',...(selected.course.anomalyRefs||[])]}else if(titleMatches.length>1||codeMatches.length>1){status='ambiguous';reason=titleMatches.length>1?'multiple-title-semester-type-matches':'duplicate-code-without-title-match'}return Object.freeze({...offering,canonicalCurriculumCourseId:selected?.relation.id??null,mappingStatus:status,mappingEvidence:Object.freeze({reason,printedCode:offering.printedCourseCode,printedTitle:offering.sourceTitle,semester:offering.semester,courseType:offering.courseType,candidateCurriculumCourseIds:(exact.length?exact:titleMatches.length?titleMatches:codeMatches).map(x=>x.relation.id)}),anomalyRefs:Object.freeze(anomalyRefs)})}
export const offerings=Object.freeze(sourceOfferings.map(reconcileOffering));
export const offeringSummary=Object.freeze(offerings.reduce((s,x)=>(s.total++,s[x.term]++,s[x.educationType]++,s[x.mappingStatus]++,s),{total:0,spring:0,fall:0,first:0,second:0,mapped:0,'mapped-with-anomaly':0,ambiguous:0,unmatched:0}));
export {sourceSnapshots};
export function filterOfferings(items,filters={}){return items.filter(item=>['term','educationType','semester','weekday'].every(key=>!filters[key]||String(item[key])===String(filters[key]))&&(!filters.department||getDepartmentCode(item)===filters.department))}
export function groupByWeekday(items){const order=['PAZARTESİ','SALI','ÇARŞAMBA','PERŞEMBE','CUMA'];return order.map(day=>({weekday:day,offerings:items.filter(item=>item.weekday===day).sort((a,b)=>a.startTime.localeCompare(b.startTime)||a.printedCourseCode.localeCompare(b.printedCourseCode,'tr'))})).filter(group=>group.offerings.length)}
export function findOverlaps(items){const m=value=>{const [h,n]=value.split(':').map(Number);return h*60+n},out=[];for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const a=items[i],b=items[j];if(a.term===b.term&&a.educationType===b.educationType&&a.semester===b.semester&&a.weekday===b.weekday&&m(a.startTime)<m(b.endTime)&&m(b.startTime)<m(a.endTime))out.push([a.id,b.id])}return out}
export function validateOfferings(items=offerings){const errors=[],ids=new Set(),rows=new Set(),valid=new Set(MAPPING_STATUSES);for(const item of items){if(ids.has(item.id))errors.push(`duplicate offering id ${item.id}`);ids.add(item.id);if(rows.has(item.sourceRowId))errors.push(`duplicate source row ${item.sourceRowId}`);rows.add(item.sourceRowId);if(!valid.has(item.mappingStatus))errors.push(`${item.id}: invalid mapping status`);if(item.mappingStatus.startsWith('mapped')&&!academicCatalog.curriculumCourses.some(x=>x.id===item.canonicalCurriculumCourseId))errors.push(`${item.id}: broken curriculum reference`);if(!item.audienceTokens.includes('EKO'))errors.push(`${item.id}: audience scope`);if(item.printedCourseCode==='EKO1202'&&normalize(item.sourceTitle)==='MATEMATİK II'&&item.canonicalCurriculumCourseId&&!item.anomalyRefs.includes('offering-printed-code-mismatch'))errors.push(`${item.id}: silent correction`)}return errors}
